### ISSUE TITLE
Locally building from Dockerfile

### ISSUE THREAD

**Issue by mkemaltas** [regel/chronograf#116]
I am trying to build and run the chronograf locally since I want to customize it and use it with additional models I am trying to add to the LoudML. 

I can build it perfectly fine using the Dockerfile. 
However when I run the built image , the following error occurs.

`standard_init_linux.go:207: exec user process caused "no such file or directory"
`

Tried it on two different machines:

- Ubuntu 16.04.4 LTS
- Docker version 18.09.3

and 

- Ubuntu 16.04.6 LTS
- Docker version 19.03.4

Can't seem to fix it. Would be glad to see any solutions.

**Comment by regel** [comment]
I love the idea 💯

Open issues if you have any questions on the implementation. To contribute new models, please open new pull-request in regel/loudml repository. 

On chronograf, see .circleci/config.yml file: CircleCI is used to build and push this image automatically and the build command is:

`docker build -t app .`

What OS and Docker engine version are you running? Do you experience similar issues with other containers?

**Comment by mkemaltas** [comment]
Thanks for the quick reply! I will definitely open more issues in this manner 😄 

I have successfully built and run a sample go project using Docker, without any errors. 

The OS and Docker engine details are as follows:


```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
```

```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:40:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
 
To be exactly sure, I just re-cloned the repository and ran `docker build -t app .` inside the chronograf directory.

The build completes 27/27 steps successfully, no issues there. 

When I run `docker run -p 8888:8888 app`  I get the same error

`standard_init_linux.go:207: exec user process caused "no such file or directory"`

**Comment by mkemaltas** [comment]
Ah solved it! 

After days worth of googling, I found out the problem. Apparently when CGO is enabled the binary is dynamically linked to a libc library which does not actually exist in the alpine container. So we need to disable CGO. 

Adding `ENV CGO_ENABLED=0` to the Dockerfile fixed it and now the image runs perfectly. 

Hopefully CGO is not needed and this won't cause further problems in the future. For now it looks good.

**Comment by rodrigo-albuquerque** [comment]
Do you mind sharing your Dockerfile? I've been trying to build this image unsuccessfully for a while.

That's the error I get with the current Dockerfile from develop branch:
```
Tried to lint /app/src/github.com/influxdata/chronograf/ui/src/loudml/constants/index.js but found no valid, enabled rules for this file type and file path in the resolved configuration.
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:427:19)
    at clearBuffer (_stream_writable.js:528:5)
    at WriteStream.Writable.uncork (_stream_writable.js:325:7)
    at /app/src/github.com/influxdata/chronograf/ui/node_modules/thread-loader/dist/worker.js:58:22
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  code: 'ERR_STREAM_DESTROYED'
}
[Error: EPIPE: broken pipe, write] {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
Makefile:65: recipe for target '.jssrc' failed
make: *** [.jssrc] Error 1
The command '/bin/sh -c cd /app/src/github.com/influxdata/chronograf && make' returned a non-zero code: 2
```
Thks

> Ah solved it!
> 
> After days worth of googling, I found out the problem. Apparently when CGO is enabled the binary is dynamically linked to a libc library which does not actually exist in the alpine container. So we need to disable CGO.
> 
> Adding `ENV CGO_ENABLED=0` to the Dockerfile fixed it and now the image runs perfectly.
> 
> Hopefully CGO is not needed and this won't cause further problems in the future. For now it looks good.

**Comment by rodrigo-albuquerque** [comment]
@regel Can you help out on this one please?

All I did was to clone develop branch, then I added the 'ENV CGO_ENABLED=0' to Dockerfile as I had the same issue with pre-built nightly image and I typed 'docker build -t app .' like you advise but I get this error:

```
Tried to lint /app/src/github.com/influxdata/chronograf/ui/src/shared/parsing/dataToCSV.js but found no valid, enabled rules for this file type and file path in the resolved configuration.
Tried to lint /app/src/github.com/influxdata/chronograf/ui/src/shared/parsing/showFieldKeys.js but found no valid, enabled rules for this file type and file path in the resolved configuration.
Tried to lint /app/src/github.com/influxdata/chronograf/ui/src/hosts/containers/HostsPage.js but found no valid, enabled rules for this file type and file path in the resolved configuration.
Tried to lint /app/src/github.com/influxdata/chronograf/ui/src/store/persistStateEnhancer.js but found no valid, enabled rules for this file type and file path in the resolved configuration.
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at Pipe.onStreamRead (internal/stream_base_commons.js:201:27)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
Tried to lint /app/src/github.com/influxdata/chronograf/ui/src/admin/reducers/index.js but found no valid, enabled rules for this file type and file path in the resolved configuration.
[Error: EPIPE: broken pipe, write] {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
[Error: EPIPE: broken pipe, write] {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
Tried to lint /app/src/github.com/influxdata/chronograf/ui/src/auth/Purgatory.js but found no valid, enabled rules for this file type and file path in the resolved configuration.
[Error: EPIPE: broken pipe, write] {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
[Error: EPIPE: broken pipe, write] {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
Tried to lint /app/src/github.com/influxdata/chronograf/ui/src/kapacitor/reducers/rules.js but found no valid, enabled rules for this file type and file path in the resolved configuration.
Tried to lint /app/src/github.com/influxdata/chronograf/ui/src/admin/containers/ProvidersPage.js but found no valid, enabled rules for this file type and file path in the resolved configuration.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[Error: EPIPE: broken pipe, write] {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:427:19)
    at clearBuffer (_stream_writable.js:528:5)
    at WriteStream.Writable.uncork (_stream_writable.js:325:7)
    at /app/src/github.com/influxdata/chronograf/ui/node_modules/thread-loader/dist/worker.js:58:22
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  code: 'ERR_STREAM_DESTROYED'
}
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:427:19)
    at clearBuffer (_stream_writable.js:528:5)
    at WriteStream.Writable.uncork (_stream_writable.js:325:7)
    at /app/src/github.com/influxdata/chronograf/ui/node_modules/thread-loader/dist/worker.js:58:22
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  code: 'ERR_STREAM_DESTROYED'
}
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:427:19)
    at clearBuffer (_stream_writable.js:528:5)
    at WriteStream.Writable.uncork (_stream_writable.js:325:7)
    at /app/src/github.com/influxdata/chronograf/ui/node_modules/thread-loader/dist/worker.js:58:22
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  code: 'ERR_STREAM_DESTROYED'
}
make: *** [.jssrc] Error 1
Makefile:65: recipe for target '.jssrc' failed
The command '/bin/sh -c cd /app/src/github.com/influxdata/chronograf && make' returned a non-zero code: 2
```

Docker version 19.03.12, build 48a66213fe

If I try the master branch I get this error:

```
$ docker build -t app .
Sending build context to Docker daemon  112.8MB
Step 1/12 : FROM gliderlabs/alpine
latest: Pulling from gliderlabs/alpine
3af99db4a5b0: Already exists
Digest: sha256:23b993692b943f0799b3f36042d8a1331557103eb4ac2c0b8ab36cab9f399f8b
Status: Downloaded newer image for gliderlabs/alpine:latest
 ---> 69bbd13383f7
Step 2/12 : MAINTAINER Chris Goller <chris@influxdb.com>
 ---> Running in edb6814c1f35
Removing intermediate container edb6814c1f35
 ---> 9ad5dd4d49cb
Step 3/12 : ENV CGO_ENABLED=0
 ---> Running in 38958fa1dbbd
Removing intermediate container 38958fa1dbbd
 ---> d331fe40d751
Step 4/12 : RUN apk add --update ca-certificates &&     rm /var/cache/apk/*
 ---> Running in 517e3eef56ac
fetch http://alpine.gliderlabs.com/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://alpine.gliderlabs.com/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
(1/1) Installing ca-certificates (20191127-r2)
Executing busybox-1.29.3-r10.trigger
Executing ca-certificates-20191127-r2.trigger
OK: 6 MiB in 12 packages
Removing intermediate container 517e3eef56ac
 ---> 347e00eea0ef
Step 5/12 : ADD chronograf /usr/bin/chronograf
ADD failed: stat /var/lib/docker/tmp/docker-builder055887250/chronograf: no such file or directory
```

Please, help. I'm stuck.
